name: Example
on: [push, pull_request]

jobs:
  tests:
    name: Example
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: "Use Node 18"
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: "Setup Chrome"
      uses: browser-actions/setup-chrome@v1

    - name: "Install"
      run: npm ci

    - name: "Prepare"
      run: npm run prepare

    - name: "Install"
      run: |
        chrome --version
        node ./dist/index.js

