name: Release
on:
  workflow_run:
    workflows: ['Tests']
    types:
      - completed
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install
      run: npm ci

    - name: Release
      run: node ./scripts/release/index.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        GIT_USER: rmoralp
        GIT_EMAIL: rafamp89@gmail.com
