name: Release
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  GIT_USER: ${{ github.actor }}
  GIT_EMAIL: "${{ github.actor }}@users.noreply.github.com"
on:
  workflow_run:
    workflows: ['Tests']
    types:
      - completed
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install
      run: npm ci

    - name: NPM Auth
      run: |
        npm config set registry https://registry.npmjs.org
        echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > .npmrc

    - name: Release
      run: node ./scripts/release/index.js
