name: Release
on:
  workflow_run:
    workflows: ['Tests']
    types:
      - completed
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install
      run: npm ci

    # - name: Github Identity
    #   run: |
    #     git config user.name "${{ github.actor }}"
    #     git config user.email "${{ github.actor }}@users.noreply.github.com"
    #     git remote set-url origin https://${{github.actor}}:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY

    # https://github.com/marketplace/actions/automated-releases-for-npm-packages
    - name: Publish
      uses: mikeal/merge-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Get version
      run: |
        echo "version=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV
        node ./scripts/addVersionToPackage.js
        git status

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "release: ${{ env.version }} [skip ci]"
        branch: main