name: Tests
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: "Use Node 18"
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: "Install"
      run: npm ci

    - name: "Tests"
      run: npm run test:ci
